databases:
  - name: inverterdb
    plan: free
    databaseName: inverter
    user: inverter

services:
  - type: web
    plan: free
    name: inverter
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn inverter.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inverterdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
