# Generated by Django 5.1.1 on 2024-10-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_worthiness', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_analysis',
            name='monthly_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyer_analysis',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
